### ISSUE TITLE
프로젝트 구조 설계

### ISSUE THREAD

**Issue by signature-hyeon** [bone-stew/popmate-be#12]
## Feature Description
- 프로젝트 구조 설계을 위해 팝업 스토어 단일 조회를 간단하게 구현한다.

## 패키지 구조
Presentation 계층
Application 계층
Domain 계층
Persistence 계층

## Todo list

- [x] 패키지 구조 설계
- [x] 팝업 스토어 단일 조회 API 생성 (틀만)
- [x] 커스텀 예외 클래스 생성 및 exceptionHandler 등록
- [x] Optional의 메서드를 사용한 예외 처리
