### ISSUE TITLE
ReservationStatus 입장 중, 입장 완료 상태 추가

### ISSUE THREAD

**Issue by signature-hyeon** [bone-stew/popmate-be#139]
## Feature Description
- 예약 상태에 방문 상태를 추가한다.
```java
// AS-IS
public enum ReservationStatus {

    SCHEDULED(0, "예약 예정"),
    IN_PROGRESS(1, "예약 중"),
    CLOSED(2, "예약 마감"),
    CANCELED(-1, "예약 중단");
```
```java
// TO-BE
public enum ReservationStatus {

    SCHEDULED(0, "예약 예정"),
    IN_PROGRESS(1, "예약 중"),
    CLOSED(2, "예약 마감"),
    ENTERING(3, "입장 중"), // 상태 추가
    ENTERED(4, "입장 완료"), // 상태 추가
    CANCELED(-1, "예약 중단");
```

## Todo list

- [x] ReservationStatus 클래스에 필드 추가
- [ ] 예약 상태가 변경되는 스케줄러 추가 (예약마감->입장중, 입장중->입장완료)
- [ ] 데이터베이스 기존 값 변경
