### ISSUE TITLE
UserReservationStatus 입장 만료 처리

### ISSUE THREAD

**Issue by signature-hyeon** [bone-stew/popmate-be#140]
## Feature Description
- 회원의 예약 상태에 입장 만료 상태를 추가한다. (해당 날짜가 지났을 때를 기점으로 한다.)

## Todo list

- [ ] UserReservationStatus 클래스에 입장 만료 상태의 필드를 추가한다.
- [ ] 입장 만료를 처리하는 스케줄러를 생성한다.
- [ ] 사용자의 방문 내역을 조회하는 API를 수정한다.
