### ISSUE TITLE
다른 타입의 매장들도 입력받을 수 있도록 카테고리 테이블 추가

### ISSUE THREAD

**Issue by signature-hyeon** [bone-stew/popmate-be#177]
## Feature Description
- 팝업스토어 외의 다른 타입의 매장도 입력받을 수 있도록 카테고리 테이블을 추가하였습니다.

## Todo list

- [ ] 카테고리 테이블 추가 및 sequence, pk 추가
- [ ] Category 클래스 추가
- [ ] 다른 도메인 클래스에 category_id 필드 추가
- [ ] 기존 API에서 필요한 부분들에 response에 category 필드 추가
