### ISSUE TITLE
prod 환경에서 ElastiCache 사용할 수 있도록 구축

### ISSUE THREAD

**Issue by signature-hyeon** [bone-stew/popmate-be#189]
## Feature Description
- prod 환경에서 ElastiCache 사용할 수 있도록 구축

## Todo list

- [ ] Amazon ElastiCache 리소스 생성
- [ ] prod yml 연결
- [ ] 배포 후 잘 동작하는지 확인
