### ISSUE TITLE
팝업스토어 예약 조회 구현

### ISSUE THREAD

**Issue by signature-hyeon** [bone-stew/popmate-be#22]
## Feature Description
- 팝업스토어 예약 조회 구현

## Todo list

사용자
- [x] 팝업스토어 상세 예약 조회
- [x] 내가 예약한 팝업스토어 목록 조회

백오피스
- [x] 팝업스토어별 일일 예약 목록 조회
