### ISSUE TITLE
전역 에러 처리

### ISSUE THREAD

**Issue by signature-hyeon** [bone-stew/popmate-be#4]
## Feature Description
- RestControllerAdvice를 사용하여 에러 로그를 발생시키고, API 응답을 처리합니다.

## Todo list

- [ ] RestControllerAdvice 핸들러 구현
- [ ] 예외 발생 시 응답 클래스 구현
- [ ] 비즈니스 로직 실행 시 커스텀 에러 클래스 구현
