### ISSUE TITLE
사용자 Wifi 목록을 통한 예약 가능 범위 여부 구현

### ISSUE THREAD

**Issue by signature-hyeon** [bone-stew/popmate-be#41]
## Feature Description
- 사용자의 wifi 목록과 백화점의 wifi를 비교하여 응답하는 기능이다.
- 예약하기 버튼 클릭시 예약 가능한 범위인지 조회한다.

## Todo list

- [x] wifi 테이블 설계
- [x] wifi 도메인 클래스 생성
- [x] 사용자의 wifi 목록과 백화점의 wifi 목록을 비교
- [x] 테스트 코드 작성
