### ISSUE TITLE
Spring REST Docs 세팅

### ISSUE THREAD

**Issue by signature-hyeon** [bone-stew/popmate-be#5]
## Feature Description
Spring REST Docs를 사용하여 테스트 코드 기반의 신뢰성 있는 API 문서를 생성되도록 한다.

## Spring REST Docs를 선택한 이유
자바 문서 자동화에는 주로 Swagger, Spring REST Docs가 사용되는데, Swagger보다 다음과 같은 이점이 있어 채택하였다.
-  테스트가 성공해야 문서가 작성되므로 신뢰성이 보장된다.
- Controller 코드의 가독성이 향상된다.

Swagger가 제공해주는 테스트 화면이 제공되지 않는다는 단점이 있지만, OAS를 사용한다면 해당 문제를 보완할 수 있다.

https://tech.kakaopay.com/post/openapi-documentation/

## asciidoc을 선택한 이유
MarkDown으로 작성할 수도 있지만, asciidoc은 include라는 강력한 기능을 제공한다. 다른 asciidoc 문서를 현재 문서로 가져와 포함시킬 수 있는 기능이다.

## Todo list

- [x] Spring REST Docs 라이브러리 설치
- [x] Spring REST Docs 세팅 및 중복되는 코드 리팩토링 (ex. prettyprint, directory명 등..)
- [x] asciidoc 설정
- [x] OAS 설정
- [x] 테스트 코드 생성
