### ISSUE TITLE
예약 테이블 컬럼 추가

### ISSUE THREAD

**Issue by signature-hyeon** [bone-stew/popmate-be#59]
## Feature Description
- 예약 테이블에 방문 시작시간, 종료시간을 추가한다.

## Todo list

- [ ] 데이터베이스 예약 테이블에 방문 시작시간, 종료시간 컬럼을 추가한다.
- [ ] 기존 데이터에 추가된 데이터를 넣어준다.
- [ ] 도메인 클래스에 필드를 추가한다.
- [ ] resultMap에 필드를 추가한다.
