### ISSUE TITLE
OpenApi Spec을 이용한 RestDocs to Swagger 변환 자동화

### ISSUE THREAD

**Issue by signature-hyeon** [bone-stew/popmate-be#62]
## Feature Description
- OpenApi Spec을 이용하여 RestDocs 문서를 Swagger로 변환한다.
- Swagger로 변환함으로써 기존 RestDocs API 문서의 장점과 함께 Swagger의 모든 기능을 사용할 수 있다.

## RestDocs 장점
- 프로덕션 코드와 API 문서를 만들기 위한 코드를 분리할 수 있다.
- 테스트 코드로 인해 검증된 API 문서를 생성할 수 있다.
- 커스텀이 자유롭다
- 
## OpenApi Spec을 이용하여 변환했을 때의 장점
- RestDocs 장점을 포함함
- 화면에서 API를 직접 호출하여 테스트해볼 수 있다

## Todo list

- [ ] OpenApi Spec 라이브러리 설치
- [ ] OpenApi Spec을 이용한 RestDocs to Swagger 변환 자동화
- [ ] 배포 시에도 보여지는지 확인
