### ISSUE TITLE
인증된 사용자 정보 기반으로 실행되도록 적용

### ISSUE THREAD

**Issue by signature-hyeon** [bone-stew/popmate-be#73]
## Feature Description
- SecurityContextHolder 내부의 인증된 사용자 정보 기반으로 동작하도록 AutheiticationPrinciple 어노테이션을 사용한다.

## Todo list
- [x] Controller에서 인증된 유저를 주입 받음
- [x] 기존의 API 스펙과 달라지는 테스트코드를 변경한다.
- [x] 테스트코드 쪽에서 인증받은 유저 식별자를 사용할 수 있도록 설정해준다.
- [ ] SecurityConfig에서 인증거쳐야할 url 패턴 지정
